### PR TITLE
feat: Implement auth-endpoint

### PR DESCRIPTION
**Pull request by A-BMT02**
Used passportJs library to implement the auth endpoint

### CODE REVIEW

**Review by mathiasayivor — CHANGES_REQUESTED** [review]
Good job! but can you use es6 module syntax? also, all codes apart from config and entry point files should be put inside /src directory
i.e You could move/rename the `passportTwitter.js` file from the root directory to /src/PassportStrategies/Twitter.js

**Comment by A-BMT02** [comment]
Used ES6 module
Put files in the correct folder
Tested and still works as expected

**Comment by mathiasayivor** [comment]
@A-BMT02 have you tested the changes to see if the code properly works? I know you'd normally add `"type": "module"` to package.json when using es6 modules. But you didn't add it to the package.json in your current commit

**Comment by A-BMT02** [comment]
Refactored the code to use ES6 Syntax
Put files in correct folders
Tested and it still works as expected

**Review by mathiasayivor — APPROVED** [review]
Great Job! Looks good to me.

**Comment by mathiasayivor** [comment]
@A-BMT02 please ensure you use conventional commits on your next commit.

**Comment by A-BMT02** [comment]
Noted @mathiasayivor

**Comment by Dun-sin** [comment]
> Noted @mathiasayivor

The instruction on how to use this easily is in the README

**Review by Dun-sin — APPROVED** [review]
Good to go

**Pull request merged**
